/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddingItems {
    }
    interface NavBar {
        "linkHoverColor": string;
        "linkOne": string;
        "linkThree": string;
        "linkTwo": string;
    }
    interface StandardText {
    }
}
declare global {
    interface HTMLAddingItemsElement extends Components.AddingItems, HTMLStencilElement {
    }
    var HTMLAddingItemsElement: {
        prototype: HTMLAddingItemsElement;
        new (): HTMLAddingItemsElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLStandardTextElement extends Components.StandardText, HTMLStencilElement {
    }
    var HTMLStandardTextElement: {
        prototype: HTMLStandardTextElement;
        new (): HTMLStandardTextElement;
    };
    interface HTMLElementTagNameMap {
        "adding-items": HTMLAddingItemsElement;
        "nav-bar": HTMLNavBarElement;
        "standard-text": HTMLStandardTextElement;
    }
}
declare namespace LocalJSX {
    interface AddingItems {
    }
    interface NavBar {
        "linkHoverColor"?: string;
        "linkOne"?: string;
        "linkThree"?: string;
        "linkTwo"?: string;
    }
    interface StandardText {
    }
    interface IntrinsicElements {
        "adding-items": AddingItems;
        "nav-bar": NavBar;
        "standard-text": StandardText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "adding-items": LocalJSX.AddingItems & JSXBase.HTMLAttributes<HTMLAddingItemsElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "standard-text": LocalJSX.StandardText & JSXBase.HTMLAttributes<HTMLStandardTextElement>;
        }
    }
}
