/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StandardText {
    }
}
declare global {
    interface HTMLStandardTextElement extends Components.StandardText, HTMLStencilElement {
    }
    var HTMLStandardTextElement: {
        prototype: HTMLStandardTextElement;
        new (): HTMLStandardTextElement;
    };
    interface HTMLElementTagNameMap {
        "standard-text": HTMLStandardTextElement;
    }
}
declare namespace LocalJSX {
    interface StandardText {
    }
    interface IntrinsicElements {
        "standard-text": StandardText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "standard-text": LocalJSX.StandardText & JSXBase.HTMLAttributes<HTMLStandardTextElement>;
        }
    }
}
